config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'articles#index'
  get 'profil', to: 'pages#profil'
  post '/:id/follow', to: 'pages#follow', as: "follow"
  post '/:id/unfollow', to: 'pages#unfollow', as: "unfollow"

  resources :articles, except: :index do
    resources :comments, only: [:new, :create]
      collection do
        get :most_popular
      end
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :articles, only: [ :index, :show, :update, :create, :destroy ]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, -> { order(created_at: :desc) }, dependent: :destroy
  has_one_attached :photo

  validates :title, presence: true
  validates :content, presence: true

  scope :popular, -> { order(views: :desc).first(3) }

  include PgSearch::Model
  pg_search_scope :search_by_title_and_content,
    against: [ :title, :content ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < Api::V1::BaseController
  acts_as_token_authentication_handler_for User, except: [ :index, :show ]
  before_action :set_article, only: [:show, :update, :destroy]

  def index
    @articles = policy_scope(Article)
  end

  def show
  end

  def update
    if @article.update(article_params)
    render :show
    else
      render_error #cf method en private
    end
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    authorize @article
    if @article.save
      render :show, status: :created
      # l'ajout du status n'est pas obligatoire, cela renvoie un Status 201 qui indique que le create a bien fonctionne
    else
      render_error
    end
  end

  def destroy
    @article.destroy
    head :no_content # renvoie une reponse sans body avec un head sans content (Status 204 No Content qui
                    # par convention correspond a une requete delete qui a bien fonctionne)
    # render json: { message: "Article deleted"}
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :photo)
  end

  def set_article
    @article = Article.find(params[:id])
    authorize @article
  end

  def render_error
    render json: { errors: @restaurant.errors.full_messages },
      status: :unprocessable_entity #status 422 le contenu du body envoyé n'est pas valide
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :most_popular]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @articles = Article.search_by_title_and_content(params[:query])
    else
      @articles = Article.all.order(created_at: :desc)
    end
  end

  def show
    @article.increment!(:views)
    @comments = Comment.last(5)
    @comment = Comment.new
    @comment.article = @article
  end

  def new
    @user = current_user
    @article = Article.new
    @article.user = @user
  end

  def create
    @user = current_user
    @article = Article.new(article_params)
    @article.user = @user
    if @article.save!
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @article.user = current_user
    if @article.update(article_params)
      flash.notice = "L'article '#{@article.title}' a bien été modifié !"
    redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path
  end

  def most_popular
    @articles = Article.order(views: :desc).first(5)
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content, :photo, :user_id)
  end
end

app/views/articles/edit.html.erb
<div class="edit-article-container w-75 mx-auto my-4 p-3">
  <h4 class='edit-article-title pl-0'>Modifie l'article "<%= @article.title %>"</h4>
  <%= render 'shared/form' %>
</div>

app/views/articles/index.html.erb
<% content_for :meta_title, "Le Blog des Comics" %>
<% content_for :meta_description, "Bienvenue sur le blog des Comics, entièrement dédié aux Comics !!" %>
<% content_for :meta_image, cl_image_path("banner.jpg") %>

<div class="index-container">
  <% if params[:query].present? %>
    <div class="title-bang">
      <h2 class="dernier">Les articles recherchés</h2>
    </div>
      <% if @articles.empty?  %>
        <p> Aucun article ne correspond à ta recherche...</p>
      <% else %>
        <div class="article-container">
          <% @articles.each do |article| %>
             <%= link_to article_path(article) do %>
              <div class="article-card">
                <% if article.photo.attached? %>
                <%= cl_image_tag article.photo.key, alt: 'Comics'%>
                <% else %>
                <%= cl_image_tag "picture_kafear" , alt: 'Comics' %>
                <% end %>
                <div class="article-card-infos">
                  <h2><%= article.title %></h2>
                  <h3>By <%= article.user.pseudo.capitalize %></h3>
                  <p><%= article.content.first(150)%>...</p>
                 </div>
              </div>
            <% end %>
          <% end %>
        </div>
       <% end %>
      <div class="back">
        <%= link_to '<i class="fas fa-undo-alt"></i>'.html_safe, root_path, class: "btn btn-secondary" %>
      </div>

  <% else %>
    <div class="title-bang">
      <h2 class="dernier">Derniers articles</h2>
      <%= cl_image_tag "bang_a3ecty", class: "bang", width: 200 %>
    </div>
    <div class="article-container">
      <% @articles.first(2).each do |article| %>
         <%= link_to article_path(article) do %>
          <div class="article-card">
            <% if article.photo.attached? %>
            <%= cl_image_tag article.photo.key, alt: 'Comics'%>
            <% else %>
            <%= cl_image_tag "picture_kafear" , alt: 'Comics' %>
            <% end %>
            <div class="article-card-infos">
              <h2><%= article.title %></h2>
              <h3>By <%= article.user.pseudo.capitalize %></h3>
              <p><%= article.content.first(150)%>...</p>
             </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="title-pow">
      <h2 class="lire">À lire également</h2>
      <%= cl_image_tag "Sound_Effects_j8hhvy", class: "pow", width: 150 %>
    </div>
    <% if @articles.size >= 3 %>
      <div class="article-container">
        <% @articles.last((@articles.size) - 2).each do |article| %>
          <%= link_to article_path(article) do %>
            <div class="article-card">
              <% if article.photo.attached? %>
                <%= cl_image_tag article.photo.key, alt: 'Comics'%>
              <% else %>
                <%= cl_image_tag "picture_kafear" , alt: 'Comics' %>
              <% end %>
              <div class="article-card-infos">
                <h2><%= article.title %></h2>
                <h3>By <%= article.user.pseudo.capitalize %></h3>
                <p><%= article.content.first(150)%>...</p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/articles/most_popular.html.erb
<% content_for :meta_title, "Le Blog des Comics: articles les plus populaires" %>
<% content_for :meta_description, "Découvrez les 5 articles les plus lus sur notre blog" %>
<% content_for :meta_image, cl_image_path("banner.jpg") %>

<h1>Articles les plus lus</h1>
<div class="popular-container">
  <div class="popular-container-details">
    <% @articles.each do |article| %>
      <%= link_to article_path(article) do %>
        <div class="article-card popular">
          <% if article.photo.attached? %>
          <%= cl_image_tag article.photo.key, alt: 'Comics'%>
          <% else %>
          <%= cl_image_tag "picture_kafear" , alt: 'Comics' %>
          <% end %>
          <div class="article-card-infos">
            <h2><%= article.title %></h2>
            <h3>By <%= article.user.pseudo.capitalize %></h3>
            <p><%= article.content.first(150)%>...</p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= image_tag "batwoman.png", alt: "batwoman", class: "super-heros-img-two" %>
</div>

app/views/articles/new.html.erb
<div class="new-container">
  <%= image_tag "green.png", alt: "green-lantern", class: "super-heros-img-one" %>
  <div class="new-container-details mb-4">
    <h1>Nouvel Article</h1>
    <%= render 'shared/form' %>
  </div>
</div>
<!-- <script>
  document.querySelector('.title-input').addEventListener('focus', function(){
    document.querySelector('.super-heros-img-one').classList.add('img-transform');
  });
</script> -->

app/views/articles/show.html.erb
<% content_for :meta_title, "Le Blog des Comics: l'article complet" %>
<% content_for :meta_description, "Découvrez l'intégralité de l'article, ainsi que les commentaires des bloggers" %>
<% content_for :meta_image, cl_image_path("banner.jpg") %>

<div class="article-details">
  <div class="article-details-img">
    <% if @article.photo.attached? %>
      <%= cl_image_tag @article.photo.key, alt: 'Comics'%>
    <% else %>
      <%= cl_image_tag "picture_kafear" , alt: 'Comics' %>
    <% end %>
  </div>
  <div class="article-details-infos">
    <div class="header">
      <div class="header-details">
        <h1><%= @article.title %></h1>
        <% if @article.views == 1 %>
          <p><%= @article.views %> vue</p>
          <% else %>
          <p><%= @article.views %> vues</p>
          <% end %>
      </div>
      <h2>By <%= @article.user.pseudo.capitalize %></h2>
    </div>

    <p><%= @article.content %> </p>
    <div class="links">
      <%= link_to "Tous les articles", root_path, class: "btn btn-secondary" %>
      <% if current_user == @article.user %>
        <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, articles_path(@article), class: "btn btn-secondary" %>
        <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_article_path(@article), class: "btn btn-secondary" %>
      <% end %>
      <% if user_signed_in? %>
        <a href="#new-comment" class="btn btn-secondary new-form">Poster un commentaire</a>
      <% else %>
        <%= link_to "Inscris-toi pour poster un commentaire", new_user_registration_path, class: "btn btn-secondary" %>
      <% end %>
      <% if user_signed_in? && current_user != @article.user%>
        <% if !current_user.is_following?(@article.user.id) %>
          <%= link_to profil_path(current_user, anchor: "user-#{@article.user.id}"), class: "btn btn-secondary" do %>
           Follow <%= @article.user.pseudo.capitalize %>
       <!--     ancre dans la partial user.html.erb -->
           <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="commentaires">
  <div class="trait"></div>
  <div class="comments">
    <h3>Les commentaires (<%= @article.comments.size %>) </h3>
    <% @article.comments.each do |comment| %>
      <div class="comments-details">
        <div class="comments-header">
          <div class="comments-title">
            <h4>De <%= comment.user.pseudo.capitalize %> </h4>
            <p class="date"><%= comment.created_at.strftime("%d.%m.%y") %></p>
          </div>
          <div class="avatar-img">
            <%= cl_image_tag comment.user.photo.key %>
          </div>
        </div>
        <p><%= comment.content %> </p>
      </div>
    <% end %>
  </div>
  <div class="formulaire-new" style="display: none" id="new-comment">
    <%= render 'comments/form' %>
  </div>
</div>