config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'articles#index'
  get 'profil', to: 'pages#profil'
  post '/:id/follow', to: 'pages#follow', as: "follow"
  post '/:id/unfollow', to: 'pages#unfollow', as: "unfollow"

  resources :articles, except: :index do
    resources :comments, only: [:new, :create]
      collection do
        get :most_popular
      end
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :articles, only: [ :index, :show, :update, :create, :destroy ]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner.html.erb
<div class="banner", style="background-image: url(<%= asset_path "banner.jpg"%>)">
  <h1>Bienvenue sur le Blog des Comics</h1>
  <div class="search_bar">
    <%= form_tag root_path, class: "search d-flex", method: :get do %>
      <div class="barre">
        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        autocomplete: "off",
        placeholder: "Entrez un titre de comics, un nom de super-heros..."
        %>
        <!-- autocomplete off pr ne pas se voir propose les precedentes recherches -->
      </div>
      <%= button_tag(type: 'button', class: "btn btn-primary recherche") do %>
        <i class="fas fa-search"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= simple_form_for (@article) do |f| %>
<%= f.input :title, :label => "Titre", input_html: { class: "title-input" } %>
<%= f.input :content, :label => "Contenu", input_html: {rows: 8} %>
<%= f.input :photo, as: :file %>
<div class="form-action d-flex justify-content-center my-3">
  <%= f.button :submit, "Valider l'article", class: "btn btn-secondary" %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if user_signed_in? %>
      <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Most popular", most_popular_articles_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Nouvel article", new_article_path, class: "nav-link" %>
          </li>
      </ul>
      <ul class="navbar-nav ml-5 avatar">
            <li class="nav-item dropdown">
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Profil", profil_path, class: "dropdown-item" %>
                <%= link_to "Deconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
      </ul>
    <% else %>
      <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
              <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
              <%= link_to "Most popular", most_popular_articles_path, class: "nav-link" %>
            </li>
      </ul>
      <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "S'inscrire", new_user_registration_path, class: "nav-link" %>
          </li>
      </ul>
    <% end %>
  </div>
</div>