config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'articles#index'
  get 'profil', to: 'pages#profil'
  post '/:id/follow', to: 'pages#follow', as: "follow"
  post '/:id/unfollow', to: 'pages#unfollow', as: "unfollow"

  resources :articles, except: :index do
    resources :comments, only: [:new, :create]
      collection do
        get :most_popular
      end
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :articles, only: [ :index, :show, :update, :create, :destroy ]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/_user.html.erb
<div id="user-<%= user.id %>" class="bloggers-card" data-user= <%= user.id  %> >
<!-- l'id est pour l'ancre de la page show article, le data user pr selection ds follow.js.erb -->
  <div  class="bloggers-card-name"  >
    <h2><%= user.pseudo.capitalize %></h2>
    <% if current_user.is_following?(user.id) %>
       <%= link_to "Unfollow", unfollow_path(user.id), class: "follow-link", data: { link: user.id }, method: :post, remote: true %>
    <% else %>
      <%= link_to "Follow", follow_path(user.id), class: "follow-link", data: { link: user.id }, method: :post, remote: true%>
    <% end %>
  </div>
  <div class="bloggers-card-articles">
    <h3>Most popular articles :</h3>
    <% user.articles.popular.each do |article| %>
      <%= link_to article_path(article) do %>
        <%= article.title %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pages/follow.js.erb
function renderUser(userHTML) {
  const user = document.querySelector("[data-user='<%= @user.id %>']");
  user.outerHTML = userHTML;
}

renderUser('<%= j render "user.html.erb", user: @user %>');

app/views/pages/profil.html.erb
<h1>Dashboard</h1>
<div class="dashboard-informations">
  <div class="user-informations">
    <h2>Mes informations</h2>
    <%= cl_image_tag current_user.photo.key, class: 'avatar-profil' %>
    <ul>
      <li><span class="bold">Prénom :</span> <%= current_user.first_name.capitalize %></li>
      <li><span class="bold">Nom :</span> <%= current_user.last_name.capitalize %></li>
      <li><span class="bold">Pseudo :</span> <%= current_user.pseudo.capitalize %></li>
      <li><span class="bold">Email :</span> <%= current_user.email %></li>
      <li><span class="bold">Followers :</span> <%= current_user.followers.count %></li>
    </ul>
    <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_user_registration_path, class: 'edit-button' %>
  </div>
  <div class="bloggers">
    <h2>Les blogueurs </h2>
    <% @users.each do |user| %>
      <%= render 'user.html.erb', user: user%>
    <% end %>
  </div>
</div>